name: Gitleaks Action
author: srinivasan
branding:
  icon: "play"
  color: "black"
description: This action runs gitleaks for push and pull request events
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install python packages
      run: pip install -r src/requirements.txt
      shell: bash

    - name: Download and install gitleaks
      shell: bash
      run: |
        set -x
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
        pwd
        ls
        tar -xvf gitleaks_8.18.4_linux_x64.tar.gz
        ls
        pwd
        mv gitleaks /usr/local/bin/

    - name: Run Gitleaks scan
      run: python src/main.py
      shell: bash
