name: build docker image

on:
  workflow_dispatch:
    inputs: 
      image_tag:
        description: 'enter the image tag'
        required: true
        type: string

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: |
          echo "Building docker image" 
