name: build docker image

on:
  workflow_dispatch:
    # inputs: 
    #   image_tag:
    #     description: 'enter the image tag'
    #     required: true
    #     type: string
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: |
          echo "Building docker image"

  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Running Test
        run: |
          echo "Running Test"
          exit 1

  deploy-image:
    name: deploy image
    needs: [ build-image, run-test ]
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Deploying docker image
        run: |
          echo "Deploying docker image"
