name: Gitleaks workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-gitleaks:
    runs-on: ubuntu-latest
    name: Running Gitleaks Scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Scanning
        uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        uses: Srinirap/gitleaks-actions@v1